language: python
python:
  - "3.8"
install:
  - pip install -r requirements-dev.txt
  - pip install coveralls
before_script: cp localsettings.py.example localsettings.py
script: coverage run --source='.' ./manage.py test
after_success:
  coveralls
notifications:
  email:
      recipients:
            - purepython@eaudeweb.ro
