from django.conf.urls import url

from bdr_management import views
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^$', RedirectView.as_view(url='companies')),

    url(r'^companies/?$',
        views.Companies.as_view(),
        name='companies'),
    url(r'^companies/filter/?$',
        views.CompaniesFilter.as_view(),
        name='companies_filter'),
    url(r'^companies/delete/?$',
        views.CompanyDeleteMultiple.as_view(),
        name='companies_delete_multiple'),
    url(r'^companies/export/excel/?$',
        views.CompaniesExcelExport.as_view(),
        name='companies_export'),
    url(r'^companies/export/json/?$',
        views.CompaniesJsonExport.as_view(),
        name='companies_export_json'),
    url(r'^companies/export/csv/?$',
        views.CompaniesCsvExport.as_view(),
        name='companies_export_csv'),
    url(r'^companies/(?P<pk>\d+)/?$',
        views.CompaniesManagementView.as_view(),
        name='companies_view'),
    url(r'^companies/account/(?P<account_uid>\w+)/?$',
        views.CompanyFilteredByAccountUID.as_view(),
        name='account_company'),

    url(r'^username/companies/',
        views.CompaniesForUsernameView.as_view(),
        name='companies_for_username'),

    url(r'^companies/add/?$',
        views.CompanyAdd.as_view(),
        name='companies_add'),
    url(r'^companies/(?P<pk>\d+)/edit/?$',
        views.CompaniesManagementEdit.as_view(),
        name='companies_edit'),
    url(r'^companies/(?P<pk>\d+)/delete/?',
        views.CompanyDelete.as_view(),
        name='companies_delete'),
    url(r'^companies/(?P<pk>\d+)/persons/add/?$',
        views.PersonManagementCreate.as_view(),
        name='persons_add'),
    url(r'^companies/(?P<pk>\d+)/name-history/?$',
        views.CompanyNameHistory.as_view(),
        name='company_name_history'),

    url(r'^companies/(?P<pk>\d+)/comment/add/?',
        views.CommentManagementCreate.as_view(),
        name='comment_add'),
    url(r'^companies/(?P<pk>\d+)/comment/(?P<comment_pk>\d+)/delete/?',
        views.CommentManagementDelete.as_view(),
        name='comment_delete'),

    url(r'^companies/(?P<pk>\d+)/reset/password/?',
        views.ResetPassword.as_view(),
        name='reset_password'),
    url(r'^companies/(?P<pk>\d+)/reset_password_company_account/?',
        views.ResetPasswordCompanyAccount.as_view(),
        name='reset_password_company_account'),
    url(r'^companies/(?P<pk>\d+)/set_company_account_owner/?',
        views.SetCompanyAccountOwner.as_view(),
        name='set_company_account_owner'),
    url(r'^companies/(?P<pk>\d+)/create/account/?',
        views.CreateAccount.as_view(),
        name='create_account'),
    url(r'^companies/(?P<pk>\d+)/create/reporting/folder/?',
        views.CreateReportingFolder.as_view(),
        name='create_reporting_folder'),

    url(r'^persons/?$',
        views.Persons.as_view(),
        name='persons'),
    url(r'^persons/filter/?$',
        views.PersonsFilter.as_view(),
        name='persons_filter'),
    url(r'^persons/export/?$',
        views.PersonsExport.as_view(),
        name='persons_export'),
    url(r'^persons/export/json/?$',
        views.PersonsExportJson.as_view(),
        name='persons_export_json'),
    url(r'^persons/(?P<pk>\d+)/?$',
        views.PersonManagementView.as_view(),
        name='persons_view'),
    url(r'^persons/(?P<pk>\d+)/edit/?$',
        views.PersonManagementEdit.as_view(),
        name='persons_edit'),
    url(r'^persons/(?P<pk>\d+)/create/account/?',
        views.CreateAccountPerson.as_view(),
        name='create_account_person'),
    url(r'^persons/(?P<pk>\d+)/disable/account/?',
        views.DisableAccountPerson.as_view(),
        name='disable_account_person'),
    url(r'^persons/(?P<pk>\d+)/enable/account/?',
        views.EnableAccountPerson.as_view(),
        name='enable_account_person'),
    url(r'^persons/(?P<pk>\d+)/delete/?',
        views.PersonManagementDelete.as_view(),
        name='persons_delete'),

    url(r'^companies/(?P<cpk>\d+)/persons/(?P<pk>\d+)/?$',
        views.PersonFromCompanyView.as_view(),
        name='person_from_company'),
    url(r'^companies/(?P<cpk>\d+)/persons/(?P<pk>\d+)/edit/?$',
        views.PersonFromCompanyEdit.as_view(),
        name='person_from_company_edit'),
    url(r'^companies/(?P<cpk>\d+)/persons/(?P<pk>\d+)/delete/?$',
        views.PersonFromCompanyDelete.as_view(),
        name='person_from_company_delete'),

    url(r'^obligations/?$',
        views.Obligations.as_view(),
        name='obligations'),
    url(r'^obligations/add/?$',
        views.ObligationCreate.as_view(),
        name='obligations_add'),
    url(r'^obligations/filter/?$',
        views.ObligationsFilter.as_view(),
        name='obligations_filter'),
    url(r'^obligations/(?P<pk>\d+)/?$',
        views.ObligationView.as_view(),
        name='obligation_view'),
    url(r'^obligations/(?P<pk>\d+)/edit/?$',
        views.ObligationEdit.as_view(),
        name='obligation_edit'),
    url(r'^obligations/(?P<pk>\d+)/delete/?$',
        views.ObligationDelete.as_view(),
        name='obligation_delete'),

    url(r'^templates/?$',
        views.EmailTemplates.as_view(),
        name='email_templates'),
    url(r'^templates/add/?$',
        views.EmailTemplateCreate.as_view(),
        name='email_templates_add'),
    url(r'^templates/filter/?$',
        views.EmailTemplatesFilter.as_view(),
        name='email_templates_filter'),
    url(r'^templates/(?P<pk>\d+)/?$',
        views.EmailTemplateView.as_view(),
        name='email_template_view'),
    url(r'^templates/(?P<pk>\d+)/edit/?$',
        views.EmailTemplateEdit.as_view(),
        name='email_template_edit'),
    url(r'^templates/(?P<pk>\d+)/delete/?$',
        views.EmailTemplateDelete.as_view(),
        name='email_template_delete'),

    url(r'^settings/?$',
        views.Settings.as_view(),
        name='settings_view'),
    url(r'^settings/edit/?$',
        views.SettingsEdit.as_view(),
        name='settings_edit'),
    url(r'^actions/?$',
        views.Actions.as_view(),
        name='actions'),
    url(r'^actions/copy-report-status/?$',
        views.CopyReportingStatus.as_view(),
        name='copy_report_status'),
]
