from django.conf.urls import url

from bdr_management.views import companies
from bdr_management.views import persons
from bdr_management.views import actions
from bdr_management.views import comments
from bdr_management.views import obligations
from bdr_management.views import email_templates
from bdr_management.views import settings_view

from django.views.generic import RedirectView


urlpatterns = [
    url(r'^$', RedirectView.as_view(url='companies')),


    # companies
    url(r'^companies/?$',
        companies.Companies.as_view(),
        name='companies'),
    url(r'^companies/filter/?$',
        companies.CompaniesFilter.as_view(),
        name='companies_filter'),
    url(r'^companies/delete/?$',
        companies.CompanyDeleteMultiple.as_view(),
        name='companies_delete_multiple'),
    url(r'^companies/export/excel/?$',
        actions.CompaniesExcelExport.as_view(),
        name='companies_export'),
    url(r'^companies/export/json/?$',
        actions.CompaniesJsonExport.as_view(),
        name='companies_export_json'),
    url(r'^companies/export/csv/?$',
        actions.CompaniesCsvExport.as_view(),
        name='companies_export_csv'),
    url(r'^companies/(?P<pk>\d+)/?$',
        companies.CompaniesManagementView.as_view(),
        name='companies_view'),
    url(r'^companies/account/(?P<account_uid>\w+)/?$',
        companies.CompanyFilteredByAccountUID.as_view(),
        name='account_company'),

    url(r'^companies/add/?$',
        companies.CompanyAdd.as_view(),
        name='companies_add'),
    url(r'^companies/(?P<pk>\d+)/edit/?$',
        companies.CompaniesManagementEdit.as_view(),
        name='companies_edit'),
    url(r'^companies/(?P<pk>\d+)/delete/?',
        companies.CompanyDelete.as_view(),
        name='companies_delete'),
    url(r'^companies/(?P<pk>\d+)/persons/add/?$',
        persons.PersonManagementCreate.as_view(),
        name='persons_add'),
    url(r'^companies/(?P<pk>\d+)/name-history/?$',
        companies.CompanyNameHistory.as_view(),
        name='company_name_history'),

    url(r'^companies/(?P<pk>\d+)/comment/add/?',
        comments.CommentManagementCreate.as_view(),
        name='comment_add'),
    url(r'^companies/(?P<pk>\d+)/comment/(?P<comment_pk>\d+)/delete/?',
        comments.CommentManagementDelete.as_view(),
        name='comment_delete'),
    url(r'^companies/(?P<pk>\d+)/reset/passwords/?',
        companies.ResetPasswords.as_view(),
        name='reset_passwords'),
    url(r'^companies/(?P<pk>\d+)/create/accounts/?',
        companies.CreateAccounts.as_view(),
        name='create_accounts'),
    url(r'^companies/(?P<pk>\d+)/create/reporting/folder/?',
        companies.CreateReportingFolder.as_view(),
        name='create_reporting_folder'),

    url(r'^companies/(?P<cpk>\d+)/persons/(?P<pk>\d+)/?$',
        persons.PersonFromCompanyView.as_view(),
        name='person_from_company'),
    url(r'^companies/(?P<cpk>\d+)/persons/(?P<pk>\d+)/edit/?$',
        persons.PersonFromCompanyEdit.as_view(),
        name='person_from_company_edit'),
    url(r'^companies/(?P<cpk>\d+)/persons/(?P<pk>\d+)/delete/?$',
        persons.PersonFromCompanyDelete.as_view(),
        name='person_from_company_delete'),


    # persons
    url(r'^persons/?$',
        persons.Persons.as_view(),
        name='persons'),
    url(r'^persons/filter/?$',
        persons.PersonsFilter.as_view(),
        name='persons_filter'),
    url(r'^persons/export/?$',
        actions.PersonsExport.as_view(),
        name='persons_export'),
    url(r'^persons/export/json/?$',
        actions.PersonsExportJson.as_view(),
        name='persons_export_json'),
    url(r'^persons/(?P<pk>\d+)/?$',
        persons.PersonManagementView.as_view(),
        name='persons_view'),
    url(r'^persons/(?P<pk>\d+)/edit/?$',
        persons.PersonManagementEdit.as_view(),
        name='persons_edit'),
    url(r'^persons/(?P<pk>\d+)/delete/?',
        persons.PersonManagementDelete.as_view(),
        name='persons_delete'),
    url(r'^person/(?P<pk>\d+)/reset/password/?',
        persons.ResetPassword.as_view(),
        name='reset_password'),
    url(r'^person/(?P<pk>\d+)/create/account/?',
        persons.CreateAccount.as_view(),
        name='create_account'),


    # obligations
    url(r'^obligations/?$',
        obligations.Obligations.as_view(),
        name='obligations'),
    url(r'^obligations/add/?$',
        obligations.ObligationCreate.as_view(),
        name='obligations_add'),
    url(r'^obligations/filter/?$',
        obligations.ObligationsFilter.as_view(),
        name='obligations_filter'),
    url(r'^obligations/(?P<pk>\d+)/?$',
        obligations.ObligationView.as_view(),
        name='obligation_view'),
    url(r'^obligations/(?P<pk>\d+)/edit/?$',
        obligations.ObligationEdit.as_view(),
        name='obligation_edit'),
    url(r'^obligations/(?P<pk>\d+)/delete/?$',
        obligations.ObligationDelete.as_view(),
        name='obligation_delete'),


    # emails
    url(r'^templates/?$',
        email_templates.EmailTemplates.as_view(),
        name='email_templates'),
    url(r'^templates/add/?$',
        email_templates.EmailTemplateCreate.as_view(),
        name='email_templates_add'),
    url(r'^templates/filter/?$',
        email_templates.EmailTemplatesFilter.as_view(),
        name='email_templates_filter'),
    url(r'^templates/(?P<pk>\d+)/?$',
        email_templates.EmailTemplateView.as_view(),
        name='email_template_view'),
    url(r'^templates/(?P<pk>\d+)/edit/?$',
        email_templates.EmailTemplateEdit.as_view(),
        name='email_template_edit'),
    url(r'^templates/(?P<pk>\d+)/delete/?$',
        email_templates.EmailTemplateDelete.as_view(),
        name='email_template_delete'),


    # settings
    url(r'^settings/?$',
        settings_view.Settings.as_view(),
        name='settings_view'),
    url(r'^settings/edit/?$',
        settings_view.SettingsEdit.as_view(),
        name='settings_edit'),
    url(r'^actions/?$',
        actions.Actions.as_view(),
        name='actions'),
    url(r'^actions/copy-report-status/?$',
        actions.CopyReportingStatus.as_view(),
        name='copy_report_status'),
]
