# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-03 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bdr_registry", "0002_make_company_fields_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bdr_registry.Country",
            ),
        ),
    ]
