# Generated by Django 3.2.4 on 2021-06-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdr_registry", "0007_auto_20210617_1331"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportingstatus",
            name="reported",
            field=models.BooleanField(null=True),
        ),
    ]
