# Generated by Django 3.2.4 on 2023-06-01 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdr_registry', '0009_alter_companynamehistory_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='companies', to='bdr_registry.account'),
        ),
        migrations.AlterField(
            model_name='person',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='persons', to='bdr_registry.account'),
        ),
    ]
